### ISSUE TITLE
[Request]: remove the give players money and collectables (banneed them)

### ISSUE THREAD

**Issue by Beginner555989** [Deadlineem/Extras-Addon-for-YimMenu#139]
### Request

guys if u still support this script can u remove the give money to player .. now with BattleEye maybe they get banned

**Comment by Deadlineem** [comment]
Giving collectibles maybe, but the money options only give like 1k each time and are limited so i don't see bans coming from this.  Then again i don't forsee bans from either of them because its not like youre passing out millions, you'd have a higher risk getting your friend banned using heist editors or casino rigging.

Also, R* added battleye, but battleye is not properly implemented into GTA5 which is how it was bypassed so quickly.
