### ISSUE TITLE
[Bug]: When starting a robbery of cayo perico or casino the game crashes

### ISSUE THREAD

**Issue by Pochemy-ux** [Deadlineem/Extras-Addon-for-YimMenu#147]
### Description

No matter what setup I choose, the game crashes after launch.

### Steps to Reproduce

1. Choose the main reward as well as the rewards that will be on the kayo map
2. Drop the killer whale
3. Start the robbery
4. When the loading appears, the game crashes

### Additional Information

I use the latest version of FSL 1.4 and also the Chronix menu mod
This happens when I go with someone to rob, but alone everything works
### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
Since 1.70 it has been freezing at "Launching Session" this is because of Battleye, there is no known fix for this at this time, it relies on fixes in YimMenu which is the main mod that chronix is based off of.  If they manage to fix it within their menu, then it may work again with others.  Do the casino rig for them instead.
