### ISSUE TITLE
update.bat needs update  for data.json

### ISSUE THREAD

**Issue by binded-zz** [Deadlineem/Extras-Addon-for-YimMenu#41]
the update.bat does not download the Extras-data.lua file that as been added
manual download works

**Comment by Deadlineem** [comment]
Really?  I thought i fixed that problem.  Make sure you are using the lates version of update.bat (technically, thats the only file you need to be updating, since it can download the rest for you.)

Yes, i indeed fixed this,

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/2cccb52051c961504ea7094736035f22fd10f517/update.bat#L113
