### ISSUE TITLE
Change the Online Player Options

### ISSUE THREAD

**Issue by froschhuepfer** [Deadlineem/Extras-Addon-for-YimMenu#69]
That you can close an open the Option Windows by a Button like a hook
right now is it a litle bit bugy 

![grafik](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/95234890/7ccbe33a-fbe8-406b-a54d-3c76cbabdf96)

Like this i want to close and open the windows that will look better is better when you dont want to have a full screen from only the menu

**Comment by Deadlineem** [comment]
We already have a plan for these options as we do not like how bloated it is either.  Our plan for this in the future will be a separate player list which will hold these features rather than extending the existing player list.  I did attempt it with the toggleable options you see there already with the checkboxes, but it was never perfected.

**Comment by froschhuepfer** [comment]
okay thx

**Comment by Deadlineem** [comment]
> okay thx

For now, the little arrows next to the tabs (Grief Options, Drop Options, Vehicle Options) can be clicked to minimize these imgui tabs, as for the toggles, that will be a project for another time.

**Comment by Deadlineem** [comment]
> okay thx

Update on your original post, the toggles were removed and in their place is a button to collapse all 3 tabs.  Still working on another method to toggle them to show/hide but for now this is alot better than it was.

**Comment by Deadlineem** [comment]
Submenus can now be moved wherever you want on screen 
![Uploading Screenshot_124.png…]()
