### ISSUE TITLE
New Ideas

### ISSUE THREAD

**Issue by ilpiruz** [Deadlineem/Extras-Addon-for-YimMenu#72]
is possible to apply a force to a player/vehicle? like the wind and push someone

**Comment by Deadlineem** [comment]
> is possible to apply a force to a player/vehicle? like the wind and push someone



> is possible to apply a force to a player/vehicle? like the wind and push someone


Select yourself and navigate in the addon to
Player Options > Fun Self Options > Magnet/Forcefield
from here you can set the forcefield magnitude/radius. 


 You cannot push a players ped as desired because it would require complete control of the player i believe, but you can push their car around since you can take control of their vehicle.

**Comment by ilpiruz** [comment]
yeah i know about these options, i was just wondering if it was possible to make the forcefield on a selected player

**Comment by Deadlineem** [comment]
`if blackHoleMarkerVisible then
         playerPed = PLAYER.GET_PLAYER_PED_SCRIPT_INDEX(network.get_selected_player())
         playerCoords = ENTITY.GET_ENTITY_COORDS(playerPed, true)
        GRAPHICS.DRAW_MARKER_SPHERE(playerCoords.x, playerCoords.y, playerCoords.z, blackHoleRadius, 255, 0, 0, 0.3)
    end`
