### ISSUE TITLE
not working options

### ISSUE THREAD

**Issue by 6516516** [Deadlineem/Extras-Addon-for-YimMenu#77]
heist setup : complete all setups not working for appartment
car gift is i gift he just get kick of the vehicle and cant enter again

**Comment by Deadlineem** [comment]
@USBMenus is the apartment heist guru

Vehicle gifting, you need to follow the guide EXACTLY (hover over the button for a large tooltip guide) as it is written.  The reason youre gifting is kicking them out is because youre not unchecking the box that says "No Pollution" which also has a tooltip on what it does.

**Comment by 6516516** [comment]
oh true .. thats because i was allways use the old version of extra add on .. and its okay if NO Pollution is selected ... (my bad) .. thank you <3
