### ISSUE TITLE
[Suggestion] Move Options For Selected Player To The Selected Player Tab

### ISSUE THREAD

**Issue by USBMenus** [Deadlineem/Extras-Addon-for-YimMenu#8]
it would be easier to navigate through the options for selected player if it was in the selected player tab, the tab shows when the script/menu is first loaded and nothing is selected, but then only shows when a player is selected and on their name
you can get the tab with `gui.get_tab("")`

**Comment by Deadlineem** [comment]
I was messing with this today actually, because I have plans to clean up the script alot more, however, most of the player selectable options are Drops, Object/Vehicle Spawners and grief options.  Once i get the script set up with most of the features im working on for the businesses, i plan to finish up the heist editor section and then start condensing things and placing things in yims actual gui tabs.

**Comment by bartikofff** [comment]
hey, I need your help with yimmenu, if you can message me in tg - @bartikofff, thank you I'll pay for help <3

**Comment by Deadlineem** [comment]
@bartikofff add my discord, same name as on github.  I can help you there!

Also @USBMenus - I put this in a discussion on yimmenu's repo, god only knows if they will address the issue with GUI_TAB_PLAYER or not, until then I wont progress adding the options there because of the box that pops up when you open the menu.

Still leaving this here though.

**Comment by Deadlineem** [comment]
Completed in v1.0, see screenshot!
![Screenshot_378](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/715f4ef4-f324-4b74-889c-1dbdcf94118a)

**Comment by bartikofff** [comment]
hey, I sent you invite to friends in discord, my name is - hibartik
