### ISSUE TITLE
SubMenus

### ISSUE THREAD

**Issue by mrnasty0306** [Deadlineem/Extras-Addon-for-YimMenu#80]
Can you add back the feature to move the submenus into the main yimmenu. They're all different colors now and there is only an option to collapse them.

**Comment by Deadlineem** [comment]
Eventually, yes.  The problem with that old option was it was severely glitched out, i may make an option to just show hide all of them entirely.

**Comment by Flylow260** [comment]
> Eventually, yes. The problem with that old option was it was severely glitched out, i may make an option to just show hide all of them entirely.

I think it would be great to separate them and have the submenu positioned like in the following image. It was organized and easy to use this way. Is it possible to arrange it like this?
![unbenannt](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/166236811/9ab60e2b-594e-4145-8617-962fb985d322)

**Comment by Deadlineem** [comment]
That was the main issue we were having, the goal was to be able to either have the collapsible tabs OR put them ALL below the main player options tab via the checkboxes, but since they all route to the same spot it caused that debug window, which is ok but the tabs arent named properly when that shows.

**Comment by Flylow260** [comment]
> That was the main issue we were having, the goal was to be able to either have the collapsible tabs OR put them ALL below the main player options tab via the checkboxes, but since they all route to the same spot it caused that debug window, which is ok but the tabs arent named properly when that shows.

Alright, thank you very much for the explanation and clarification. I just wanted to ask if it is still possible, because it is not really a big issue that a debug window opens, and it was always quite useful since it can be moved around, giving a bit more freedom in terms of layout. Or do you prefer to do it completely differently? Because with the three-colored system now, it's not a big deal, but I find it not as easily viewable since you can't see all three at the same time.

**Comment by Deadlineem** [comment]
We had plans to make another player list and moving these options there, but i personally wanted YimMenu's player options to have a show hide toggle bc its so large in general

https://github.com/YimMenu/YimMenu/issues/3224

**Comment by Deadlineem** [comment]
> > That was the main issue we were having, the goal was to be able to either have the collapsible tabs OR put them ALL below the main player options tab via the checkboxes, but since they all route to the same spot it caused that debug window, which is ok but the tabs arent named properly when that shows.
> 
> Alright, thank you very much for the explanation and clarification. I just wanted to ask if it is still possible, because it is not really a big issue that a debug window opens, and it was always quite useful since it can be moved around, giving a bit more freedom in terms of layout. Or do you prefer to do it completely differently? Because with the three-colored system now, it's not a big deal, but I find it not as easily viewable since you can't see all three at the same time.

SubMenus can now be moved anywhere on the screen.
![Screenshot_124](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/91760fea-8eb5-46f7-9a10-4b44dd6be100)
![Screenshot_125](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/dfe4c70b-ec9b-40e8-ba5b-c7dd8300abb1)
