### ISSUE TITLE
[BUG]  Cayo Perico Heist Editor some things not working

### ISSUE THREAD

**Issue by rjp421** [Deadlineem/Extras-Addon-for-YimMenu#93]
Skip Cooldown, and Reset Kosatka Board no longer work while you are near the planning screen.

I have to go to the Sparrow area to change the Presets and Skip/Reset.

No longer works:
- Skip Drainage Cut
- Skip Fingerprint Scanner
- Skip Glass Cut

- Remove All CCTV's (removes most of them, sometimes)

Some of the Teleports can only be used when you are near them, i.e. Drainage.

Using YimMenu build 61ddba1 from today.

Thanks for the Extras!

**Comment by Deadlineem** [comment]
> Skip Cooldown, and Reset Kosatka Board no longer work while you are near the planning screen.
> 
> I have to go to the Sparrow area to change the Presets and Skip/Reset.
> 
> No longer works:
> 
> * Skip Drainage Cut
> * Skip Fingerprint Scanner
> * Skip Glass Cut
> * Remove All CCTV's (removes most of them, sometimes)
> 
> Some of the Teleports can only be used when you are near them, i.e. Drainage.
> 
> Using YimMenu build 61ddba1 from today.
> 
> Thanks for the Extras!

Ill be pushing an update to fix everything EXCEPT the teleports in a moment.

The reason the teleports don't work until you are close is because they are Blip Teleports

As for the CCTV's, it has always worked pretty much the way it does now, the only thing we can do to that is maybe add more CCTV ID's if we can locate them.
